[project]
name = "leetcode-python"
version = "0.1.0"
description = "LeetCode implemented by Python"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4",
    "pytest-cov>=6.2",
    "ruff>=0.12",
]
