name: Continuous Integration

on:
  push:
    branches: [ "main" ]
    paths: [ "**/*.py" ]
  pull_request:

jobs:
  run_test_and_upload_codecov:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Dependencies
        run: pip install pytest pytest-cov
      - name: Generate Coverage
        run: pytest --cov=src --cov-report=xml
      - name: Upload Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: shilin83/leetcode-python
          fail_ci_if_error: true
          verbose: true
